# Steps to generate the "Documentation" directory
#
# PROMPT> pwd
# /Users/username/deep/path/to/radiantforms-ios
# PROMPT> jazzy --config .github/jazzy.yml
# Using config file /Users/username/deep/path/to/radiantforms-ios/.github/jazzy.yml
# Running xcodebuild
# ...
# building search index
# jam out ♪♫ to your fresh new docs in `Documentation`
# PROMPT>

theme: fullwidth

output: ../Documentation

xcodebuild_arguments: [-workspace, RadiantForms.xcworkspace, -scheme, RadiantForms]
